-- CreateTable
CREATE TABLE "DriftPositions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "action" TEXT NOT NULL,
    "actionExplanation" TEXT NOT NULL,
    "baseAssetAmountFilled" TEXT NOT NULL,
    "bitFlags" INTEGER NOT NULL,
    "fillRecordId" INTEGER NOT NULL,
    "filler" TEXT NOT NULL,
    "fillerReward" REAL NOT NULL,
    "maker" TEXT NOT NULL,
    "makerFee" REAL NOT NULL,
    "makerOrderBaseAssetAmount" REAL NOT NULL,
    "makerOrderCumulativeBaseAssetAmountFilled" REAL NOT NULL,
    "makerOrderCumulativeQuoteAssetAmountFilled" REAL NOT NULL,
    "makerOrderDirection" TEXT NOT NULL,
    "makerOrderId" INTEGER NOT NULL,
    "makerRebate" REAL NOT NULL,
    "marketFilter" TEXT NOT NULL,
    "marketIndex" INTEGER NOT NULL,
    "marketType" TEXT NOT NULL,
    "oraclePrice" REAL NOT NULL,
    "quoteAssetAmountFilled" REAL NOT NULL,
    "quoteAssetAmountSurplus" REAL NOT NULL,
    "referrerReward" REAL NOT NULL,
    "slot" INTEGER NOT NULL,
    "spotFulfillmentMethodFee" REAL NOT NULL,
    "symbol" TEXT NOT NULL,
    "taker" TEXT NOT NULL,
    "takerFee" REAL NOT NULL,
    "takerOrderBaseAssetAmount" REAL NOT NULL,
    "takerOrderCumulativeBaseAssetAmountFilled" REAL NOT NULL,
    "takerOrderCumulativeQuoteAssetAmountFilled" REAL NOT NULL,
    "takerOrderDirection" TEXT NOT NULL,
    "takerOrderId" INTEGER NOT NULL,
    "ts" DATETIME NOT NULL,
    "txSig" TEXT NOT NULL,
    "txSigIndex" INTEGER NOT NULL,
    "user" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "DriftPositions_txSig_key" ON "DriftPositions"("txSig");
